-- =============================================================================
-- 00_setup.sql  |  One-time Snowflake bootstrap (run as ACCOUNTADMIN / SECURITYADMIN)
-- Creates: database, schemas, warehouses, roles, grants, cost guard-rails.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- ---------- Compute -----------------------------------------------------------
-- Separate warehouses so ELT, BI and ML never queue behind each other.
CREATE WAREHOUSE IF NOT EXISTS AMS_TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'dbt builds and raw loads';
CREATE WAREHOUSE IF NOT EXISTS AMS_BI_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Streamlit / analyst queries';

-- Hard stop on spend: 20 credits / month, notify at 75%, suspend at 100%.
CREATE RESOURCE MONITOR IF NOT EXISTS AMS_MONITOR
  WITH CREDIT_QUOTA = 20 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE AMS_TRANSFORM_WH SET RESOURCE_MONITOR = AMS_MONITOR;
ALTER WAREHOUSE AMS_BI_WH        SET RESOURCE_MONITOR = AMS_MONITOR;

-- ---------- Storage -----------------------------------------------------------
CREATE DATABASE IF NOT EXISTS ATHLETE_DB;
USE DATABASE ATHLETE_DB;

CREATE SCHEMA IF NOT EXISTS RAW           COMMENT = 'Source-system extracts, loaded as-is';
CREATE SCHEMA IF NOT EXISTS STAGING       COMMENT = 'dbt: cleaned, typed, deduplicated 1:1 with sources';
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE  COMMENT = 'dbt: dense athlete-day spine, rolling windows';
CREATE SCHEMA IF NOT EXISTS MARTS         COMMENT = 'dbt: dimensional models + ML feature marts';
CREATE SCHEMA IF NOT EXISTS ML            COMMENT = 'Model outputs written back by Python (scores, recommendations, metrics)';
CREATE SCHEMA IF NOT EXISTS REFERENCE     COMMENT = 'dbt seeds: targets, lever catalog, position groups';

-- ---------- Roles (least privilege) ----------------------------------------
CREATE ROLE IF NOT EXISTS AMS_LOADER;      -- writes RAW only
CREATE ROLE IF NOT EXISTS AMS_TRANSFORMER; -- reads RAW, owns everything dbt builds
CREATE ROLE IF NOT EXISTS AMS_ML;          -- reads MARTS, writes ML
CREATE ROLE IF NOT EXISTS AMS_ANALYST;     -- read-only on MARTS + ML + REFERENCE

GRANT USAGE ON DATABASE ATHLETE_DB TO ROLE AMS_LOADER;
GRANT USAGE ON DATABASE ATHLETE_DB TO ROLE AMS_TRANSFORMER;
GRANT USAGE ON DATABASE ATHLETE_DB TO ROLE AMS_ML;
GRANT USAGE ON DATABASE ATHLETE_DB TO ROLE AMS_ANALYST;

-- loader
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA RAW TO ROLE AMS_LOADER;
GRANT ALL ON ALL TABLES IN SCHEMA RAW TO ROLE AMS_LOADER;
GRANT ALL ON FUTURE TABLES IN SCHEMA RAW TO ROLE AMS_LOADER;
GRANT USAGE ON WAREHOUSE AMS_TRANSFORM_WH TO ROLE AMS_LOADER;

-- transformer (dbt)
GRANT USAGE ON SCHEMA RAW TO ROLE AMS_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE AMS_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE AMS_TRANSFORMER;
GRANT USAGE ON SCHEMA ML TO ROLE AMS_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA ML TO ROLE AMS_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ML TO ROLE AMS_TRANSFORMER;
GRANT ALL ON SCHEMA STAGING, INTERMEDIATE, MARTS, REFERENCE TO ROLE AMS_TRANSFORMER;
GRANT USAGE ON WAREHOUSE AMS_TRANSFORM_WH TO ROLE AMS_TRANSFORMER;

-- ML
GRANT USAGE ON SCHEMA MARTS, REFERENCE TO ROLE AMS_ML;
GRANT SELECT ON ALL TABLES IN SCHEMA MARTS     TO ROLE AMS_ML;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS  TO ROLE AMS_ML;
GRANT SELECT ON ALL TABLES IN SCHEMA REFERENCE TO ROLE AMS_ML;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REFERENCE TO ROLE AMS_ML;
GRANT ALL ON SCHEMA ML TO ROLE AMS_ML;
GRANT USAGE ON WAREHOUSE AMS_TRANSFORM_WH TO ROLE AMS_ML;

-- analyst / BI
GRANT USAGE ON SCHEMA MARTS, ML, REFERENCE TO ROLE AMS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MARTS     TO ROLE AMS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS  TO ROLE AMS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ML        TO ROLE AMS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ML     TO ROLE AMS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA REFERENCE TO ROLE AMS_ANALYST;
GRANT USAGE ON WAREHOUSE AMS_BI_WH TO ROLE AMS_ANALYST;

-- ---------- Wire roles to the service user you create -----------------------
-- CREATE USER ams_svc PASSWORD = '***' DEFAULT_ROLE = AMS_TRANSFORMER DEFAULT_WAREHOUSE = AMS_TRANSFORM_WH;
-- GRANT ROLE AMS_LOADER, AMS_TRANSFORMER, AMS_ML TO USER ams_svc;
-- Prefer key-pair auth for the service user in anything beyond a demo.

-- ---------- Optional: mask nothing here, but this is where row/column policies
-- (e.g. restricting medical injury detail to the AMS_MEDICAL role) would live.
