-- =============================================================================
-- 01_raw_tables.sql  |  RAW layer DDL. Types mirror the source feeds exactly;
-- no cleaning happens here (that is dbt staging's job).
-- =============================================================================
USE ROLE AMS_LOADER;
USE WAREHOUSE AMS_TRANSFORM_WH;
USE SCHEMA ATHLETE_DB.RAW;

CREATE OR REPLACE TABLE ATHLETES (
  ATHLETE_ID VARCHAR, TEAM_ID VARCHAR, POSITION VARCHAR, BIRTH_DATE DATE,
  HEIGHT_CM FLOAT, WEIGHT_KG FLOAT, DOMINANT_FOOT VARCHAR, SIGNED_DATE DATE,
  _LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE FIXTURES (
  FIXTURE_ID NUMBER, TEAM_ID VARCHAR, FIXTURE_DATE DATE, COMPETITION VARCHAR,
  HOME_AWAY VARCHAR, OPPONENT_STRENGTH NUMBER, _LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE TRAINING_SESSIONS (
  SESSION_ID VARCHAR, ATHLETE_ID VARCHAR, SESSION_DATE DATE, SESSION_TYPE VARCHAR,
  DURATION_MIN FLOAT, RPE FLOAT, TOTAL_DISTANCE_M FLOAT, HSR_DISTANCE_M FLOAT,
  SPRINT_COUNT FLOAT, MAX_SPEED_RAW FLOAT, SPEED_UNIT VARCHAR, PLAYER_LOAD FLOAT,
  AVG_HR_BPM FLOAT, GPS_VENDOR VARCHAR, _LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE WELLNESS_DAILY (
  ATHLETE_ID VARCHAR, WELLNESS_DATE DATE, HRV_RMSSD_MS FLOAT, RESTING_HR_BPM FLOAT,
  SORENESS_1_10 FLOAT, FATIGUE_1_10 FLOAT, STRESS_1_10 FLOAT, MOOD_1_10 FLOAT,
  _LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE SLEEP_DAILY (
  ATHLETE_ID VARCHAR, SLEEP_DATE DATE, SLEEP_HOURS FLOAT, SLEEP_EFFICIENCY_PCT FLOAT,
  DEEP_SLEEP_PCT FLOAT, SOURCE_DEVICE VARCHAR, _LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE NUTRITION_DAILY (
  ATHLETE_ID VARCHAR, NUTRITION_DATE DATE, KCAL FLOAT, PROTEIN_G FLOAT, CARBS_G FLOAT,
  FAT_G FLOAT, HYDRATION_L FLOAT, _LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE INJURIES (
  INJURY_ID VARCHAR, ATHLETE_ID VARCHAR, INJURY_DATE DATE, BODY_PART VARCHAR,
  INJURY_TYPE VARCHAR, MECHANISM VARCHAR, DAYS_OUT NUMBER, OCCURRED_DURING VARCHAR,
  _LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE MATCH_PLAYER_STATS (
  MATCH_STAT_ID VARCHAR, FIXTURE_ID NUMBER, ATHLETE_ID VARCHAR, MATCH_DATE DATE,
  MINUTES_PLAYED NUMBER, STARTED BOOLEAN, PERFORMANCE_RATING FLOAT, GOALS NUMBER,
  ASSISTS NUMBER, XG FLOAT, XA FLOAT, PASS_ACCURACY_PCT FLOAT, DUELS_WON_PCT FLOAT,
  _LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE PHYSICAL_TESTS (
  TEST_ID VARCHAR, ATHLETE_ID VARCHAR, TEST_DATE DATE, CMJ_CM FLOAT, SPRINT_30M_S FLOAT,
  YOYO_IR1_M NUMBER, SQUAT_1RM_REL FLOAT, NORDIC_N FLOAT, BODY_FAT_PCT FLOAT,
  _LOADED_AT TIMESTAMP_NTZ
);

-- ML output tables. ml/*.py writes them with write_pandas (auto-create + overwrite), but they are declared
-- here so grants and dbt source tests work before the first model run. Columns mirror ml/train.py + ml/recommend.py.
USE SCHEMA ATHLETE_DB.ML;
CREATE TABLE IF NOT EXISTS INJURY_RISK_SCORES (
  ATHLETE_ID VARCHAR, DATE_DAY DATE, INJURY_RISK_7D FLOAT, RISK_BAND VARCHAR,
  DATA_SPLIT VARCHAR, MODEL_VERSION VARCHAR, SCORED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS PERFORMANCE_PREDICTIONS (
  ATHLETE_ID VARCHAR, DATE_DAY DATE, PREDICTED_RATING FLOAT, DATA_SPLIT VARCHAR,
  MODEL_VERSION VARCHAR, SCORED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS LEVER_RECOMMENDATIONS (
  ATHLETE_ID VARCHAR, AS_OF_DATE DATE, LEVER_ID VARCHAR, CURRENT_VALUE FLOAT, TARGET_VALUE FLOAT,
  RECOMMENDED_STEP FLOAT, EXPECTED_RATING_GAIN FLOAT, EXPECTED_RISK_REDUCTION_PP FLOAT,
  EXPECTED_RELATIVE_RISK_REDUCTION FLOAT, PRIORITY_SCORE FLOAT, PRIORITY_RANK NUMBER,
  N_STATE_ROWS NUMBER, MODEL_VERSION VARCHAR, SCORED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS MODEL_METRICS (
  MODEL_NAME VARCHAR, MODEL_VERSION VARCHAR, METRIC VARCHAR, VALUE FLOAT, DATA_SPLIT VARCHAR,
  TRAINED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS FEATURE_IMPORTANCE (
  FEATURE VARCHAR, IMPORTANCE_MEAN FLOAT, IMPORTANCE_STD FLOAT, MODEL_NAME VARCHAR, MODEL_VERSION VARCHAR
);
CREATE TABLE IF NOT EXISTS CALIBRATION_CURVE (
  BIN NUMBER, MEAN_PREDICTED FLOAT, OBSERVED_RATE FLOAT, N NUMBER, MODEL_NAME VARCHAR, MODEL_VERSION VARCHAR
);
CREATE TABLE IF NOT EXISTS RECOMMENDATION_VALIDATION (
  LEVER_ID VARCHAR, N_ATHLETES NUMBER, MEAN_MODEL_RATING_GAIN FLOAT, MEAN_TRUE_RATING_GAIN FLOAT,
  SPEARMAN_RATING FLOAT, MEAN_MODEL_REL_RISK_REDUCTION FLOAT, MEAN_TRUE_REL_RISK_REDUCTION FLOAT,
  SPEARMAN_RISK FLOAT, MODEL_VERSION VARCHAR
);
